mqtt:
  scheme: tcp
  host: putty.bellwether.link
  port: 1883
  clientId: LabViewData
  username: bw
  password: coffee
  topic: LabView/1

file:
  extension: .csv
  heading:
    fields:
      # line number, separator, field position, field name
      - 1, ,3,serialNumber
      - 2, ,3,partNumber
  name:
    fields:
      # separator, field position, field name
      -  " ,1,timeStamp"

  data:
    headerPrefix: test_number
    fields:
      # field position, field name
      - 1, testNumber
      - 2, testName
      - 3, lowerLimit
      - 4, upperLimit
      - 5, measuredValue
      - 6, status


