mqtt:
  scheme: tcp
  host: localhost
  port: 1883
  clientId: M707
  username:
  password:
  topic: testing/roaster/M77/panels

file:
  extension: .csv
  heading:
    fields:
      # line number, separator, field position, field name
      - 1, ,3,serialNumber
      - 2, ,3,partNumber
  name:
    fields:
      # separator, field position, field name
      -  " ,1,timeStamp"

  data:
    headerPrefix: test_number
    fields:
      # field position, field name
      - 1, testNumber
      - 2, testName
      - 3, lowerLimit
      - 4, upperLimit
      - 5, measuredValue
      - 6, status


