# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
          
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Execute tests
        run: go test ./tests
        
    
   
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
          
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Execute tests
        run: env GOOS=windows GOARCH=amd64 go build -o ./build .
